kind: pipeline
name: default

steps:
- name: test
  image: golang
  commands:
  - go build
- name: docker  
  image: plugins/docker
  commands: ["--insecure-registry","172.20.10.70:5000"]
  settings:
    repo: 172.20.10.70:5000/handyboss
    tags: latest
  