kind: pipeline
name: default

steps:
- name: test
  image: golang
  commands:
  - go build
- name: docker  
  image: plugins/docker
  settings:
    registry: 172.20.10.70:5000
    repo: 172.20.10.70:5000/handyboss
    tags: latest
  